[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.24"
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/'
]
optimizer_runs = 1_000_000
via_ir = true

[fmt]
line_length = 120
multiline_func_header = "params_first"